server {
  # listen 127.255.255.2:8082;
  listen 127.0.0.1:8080;
  # listen 127.255.255.2:8084;
  # listen 127.255.255.2:8083;
  # listen 127.255.255.3:8086;

  server_name site1.local;

  root ./www/site1;

  client_max_body_size 100000000;

  error_page 404 ./www/site1/errors/404.html;
  error_page 405 ./www/site1/errors/405.html;
  error_page 413 ./www/site1/errors/413.html;
  error_page 500 ./www/site1/errors/500.html;

  location / {
    index index.html;
    autoindex off;
  }

  location /assets {
    allowed_methods GET;
    root ./www/site1/static;
    autoindex off;
  }


  location /list {
    allowed_methods GET;
    root ./www/site1/public-list;
    autoindex on;
  }

  location /old {
    allowed_methods GET;
    return 301 /new/;
  }

  location /new {
    allowed_methods GET;
    return 301 /new/;
  }

  location /new/ {
    allowed_methods GET;
    root ./www/site1/pages/new;
    index new_page.html;
    autoindex on;
  }

  location /upload {
    allowed_methods POST;
    upload on;
    upload_dir ./www/site1/uploads;
  }

  location /uploads/ {
    allowed_methods GET DELETE;
    root ./www/site1/uploads;
    autoindex on;
  }

  location /cgi-bin {
    allowed_methods GET POST;
    root ./www/site1/cgi-bin/cgi-bin;
    cgi_ext .py /usr/bin/python3;
    cgi_ext .sh /bin/bash;
  }
}

# server {
#   listen 127.255.255.2:9090;
#   listen 127.255.255.2:8082;
#   server_name site2.local;

#   root ./www/site2;
#   client_max_body_size 200000;

#   error_page 404 ./www/site2/errors/404.html;
#   error_page 500 ./www/site2/errors/500.html;

#   location / {
#     allowed_methods GET;
#     index index.html;
#     autoindex off;
#   }

#   location /readonly {
#     allowed_methods GET;
#     root ./www/site2/pages/readonly;
#     index readonly;
#     autoindex off;
#   }
# }
